### PR TITLE
v2.4.2

### PR DESCRIPTION
**Pull request by Xaxxis**
- Fix error handling 
- Return exception when server-key is null, empty, contain white-space
- Add idempotency-key feature
- Add API registerCard, cardToken, cardPointInquiry, getStatusB2b, createSnapUrl
- Refactor ApiRequestor.php (all API request, will process from this file)
- Deprecated SnapApiRequestor.php (no longer use, will delete this on the next major release)
- Add extension curl, JSON PHP require on composer file
- Refactor unit test
- Update some PHP docs format in description function/class

### CODE REVIEW

**Review by rizdaprasetya — APPROVED** [review]
Looks good, I found no issue 👍  
please proceed to merge & create new release version. Thanks!

**Comment by rizqyhi** [comment]
Hello @rizdaprasetya @Xaxxis, is there any reason why the test namespace was removed on this MR?

I'm currently writing integration test for my project and it needs `MT_Tests` class. Since it has no namespace, I always got this error:
```
Error : Class 'MT_Tests' not found
```
Using root namespace (`\MT_Tests`) or use statement (`use MT_Tests;`) isn't working either. Is there any other workaround for this issue?

Thank you.

**Comment by Xaxxis** [comment]
Hi @rizqyhi  thank you for asking, looks like valid, will check on this and get back to you

**Comment by rizqyhi** [comment]
Hi @Xaxxis, I'm currently use 7.4. I've made a fork yesterday and worked as expected. Do you mind if I PR it?

**Comment by Xaxxis** [comment]
Hi, @rizqyhi Thank you for your contribution, really appreciated it. The fix is already on PR, we still waiting for a review for release. I Will let you know if already released

**Comment by Xaxxis** [comment]
Hi @rizqyhi the fix has been released with a new version.
Let me know if you still facing something went wrong, thank you

**Pull request merged**
