### PR TITLE
update composer

### PR DESCRIPTION
**Pull request by rizkytegar**

### CODE REVIEW

**Comment by Xaxxis** [comment]
Hi @rizkytegar thanks for your contribution, really appreciate it. Please explain further what is the Pull Request, or it will be considered as invalid and will be closed.

Thank you

**Comment by mjamilasfihani** [comment]
Maybe you can make new branch for old version? So let the main branch as the default one, with min requirement.

i.e php-x  (x is the version name)

**Comment by mjamilasfihani** [comment]
Since php5.x is really dead, I'm not recommend to lower the minimum requirement. If you need it for your purpose only, do not do PR. I suggest to make your own repo than connect it with composer.

What if main repo has update? Than it's your job as developer 😊

Cheers, Jamil

**Comment by mjamilasfihani** [comment]
It's just opinion, take it easy. Still, everything is under the owner decision.

**Comment by Xaxxis** [comment]
Hi, @mjamilasfihani  thanks for your thoughts. Yes, we do not recommend downgrading the PHP version. The reason we're still keeping the minimum version with PHP 5 is user backward compatibility. 

Correct, if you need the specific PHP version for personal purposes, you can update it on your personal repo. 
Will closed this PR due to lack of explanation from the submitter.

Thank you

**Pull request closed without merging**
